#!/usr/bin/env bash
# This script displays "Best School" 10 times, adding "Hi" after the 9th
i=0
while [ "$i" -lt 10 ]
do
	i=$((i + 1))
	printf "Best School\n"
	if [ "$i" -eq 9 ]
	then
		printf "Hi\n"
	fi
done
